# Generated by Django 5.1.4 on 2025-02-18 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Vendedor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
