# Generated by Django 5.1.4 on 2025-02-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_detallefactura_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
