# Generated by Django 5.1.4 on 2025-02-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=50)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('Funda', 'Funda'), ('Auricular', 'Auricular'), ('Cargador', 'Cargador'), ('Protec. Pantalla', 'Protec. Pantalla')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=50)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('version_ios', models.CharField(max_length=50)),
                ('porcentaje_bateria', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=50)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('pantalla', models.CharField(max_length=50)),
                ('version_ios', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('foto', models.ImageField(upload_to='productos/fotos_extra/')),
                ('es_principal', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
