# Generated by Django 5.1.4 on 2025-03-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_accesorio_costo_accesorio_numero_orden_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesorio",
            name="cantidad",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
