# Generated by Django 5.1.4 on 2025-06-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_accesorio_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iphone",
            name="imei",
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="mac",
            name="imei",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
